#!/bin/bash

set -e

a=
b=
c=
x="`xrandr | grep -o  ".* connected" | cut -d' ' -f1 `"

for f in LVDS VGA DVI-D HDMI
do
	if [[ "$x" =~ $f-. ]]
	then
		c=$b
		b=$a
		a=${BASH_REMATCH[0]}
	fi
done
printf "a: %s\nb: %s\nc: %s\n" $a $b $c

if [[ -n $c ]]
then
	xrandr --output $c --off
fi

[[ -n $a ]]


xrandr --output $a --preferred --primary


if [[ -n $b ]]
then
	xrandr --output $b --preferred --${1:-left-of} $a
fi

echo 'awesome.restart()' | awesome-client
