#!/bin/bash

echo ask about every package that is neither in base, base-devel or listed in ~/p/pacmanPackagesToKeep
for x in `comm -23 <(pacman -Qqen|sort) <((pacman -Qqg base base-devel; cat ~/p/pacmanPackagesToKeep | sed 's/\s*#.*$//'; )|sort -u)`
do
	echo $'\n\n\n'
	pacman -Qi $x

	while read -n 1 -p "Keep, keep with Comment, Remove, Ignore, make Dependency, keep All?  <$x>? [k/c/r/I/d/a]: " r
	do
		echo
		case "$r" in
			k|keep)
				echo -e "$x" >> ~/p/pacmanPackagesToKeep
			;;
			c|comment)
				read -e -p "Comment: " c &&
				echo -e "$x\t#$c" >> ~/p/pacmanPackagesToKeep 
			;;
			r|remove)
				sudo pacman -Rcu $x
			;;
			''|i|ignore)
				true
			;;
			d|dependency)
				sudo pacman -S --asdeps $x
			;;
			a|all)
				break 2
			;;
		esac && break
	done
done

echo remove abandoned dependencies
while a=`pacman -Qtdq`
do
	sudo pacman -Rcu $a
done

echo remove pkg files of packages not installed
sudo pacman -Sc

echo Ask about all *.pac{new,save} files
sudo pacdiff
