#!/bin/bash

set -e
country='DE'
sudo true

url="https://www.archlinux.org/mirrorlist/?country=$country&protocol=https&protocol=http&ip_version=4&use_mirror_status=on"

tmpfile=$(mktemp --suffix=-mirrorlist)
tmpfile2=$(mktemp --suffix=-mirrorlist-sorted)

wget -qO- "$url" | sed 's/^#Server/Server/g' > "$tmpfile"
echo got list
rankmirrors -n 6 "$tmpfile" > "$tmpfile2"
echo sorted list
sudo mv -i /etc/pacman.d/mirrorlist /etc/pacman.d/mirrorlist.orig
echo backed up
sudo mv -i "$tmpfile2" /etc/pacman.d/mirrorlist
echo activated new
sudo pacman -Syy
echo done
