#!/bin/bash

if ! modprobe vboxdrv &> /dev/null
then
	if ! gksudo  -- bash -c "modprobe vboxdrv;modprobe vboxnetadp;modprobe vboxnetflt;modprobe vboxpci";
	then
		exit $?
	fi

fi
/usr/bin/virtualbox &>/dev/null
